### ISSUE TITLE
Ubuntu 17.10 Gnome

### ISSUE THREAD

**Issue by CliffS** [majestrate/wterm#2]
Running Ubuntu 17.10 using the Gnome option (rather than the Ubuntu one) at login:

```
wl_surface@16: error 3: buffer committed to unconfigured xdg_surface
Connection error
```

Any suggestions?

**Comment by majestrate** [comment]
wterm broke a while back and I never could figure out what changes in compositors made this happen.

this project has been on back burner for a bit so it has yet to be properly fixed, any additional eyes 
on the code to figure that out would be super.

**Comment by majestrate** [comment]
try latest commit.

**Comment by CliffS** [comment]
Just tried wterm again.  It seems to work but I get no window decoration.  Is this expected behaviour?  Or am I doing something wrong?

**Comment by majestrate** [comment]
if gnome requires client side decorators now then it's the expected behavior.

**Comment by CliffS** [comment]
> if gnome requires client side decorators now then it's the expected behavior.

Seems that Wayland does require CSD.

**Comment by majestrate** [comment]
If I recall correctly that's GNOME pushing that, sway does not and probably will not require CSD. I won't support CSD. CSD brings an inconstant UX because in the end every toolkit wants to style differently.

**Comment by majestrate** [comment]
If you want CSD support you'll have to maintain that feature yourself, I'll take patches but it'll be your responsibility for code maintenance.

A good read on wayland CSD https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html

**Comment by CliffS** [comment]
I am very confused and not at all an expert on X, Wayland, GNOME etc.  I understand the political argument and I agree with your point of view.

However, what is confusing me is this:

* I run `xterm` (which presumably does not have CSD) and I get a titlebar.  
* I run `wterm` which we know doesn't have CSD and I don't get a titlebar.

So where is the titlebar coming from in xterm and why don't I see it in wterm?

**Comment by majestrate** [comment]
xterm is an x11 application, it runs in xwayland, the xserver takes care of the titlebar and such.
wterm is a wayland application, the titlebar protocol is not yet agreed on as the ecosystem is halfbaked.

**Comment by CliffS** [comment]
Interesting.  But that does make this project less than useful at the moment.  It would be great if you could add in a header bar and then I could start using this as my main terminal program.

**Comment by majestrate** [comment]
If the GNOME people want CSD they're going to have to put in the work themselves instead of using FUD to rally their userbase to demand others do the work for them.
