### ISSUE TITLE
Undeclared variable VERSION

### ISSUE THREAD

**Issue by MichaelMackus** [majestrate/wterm#6]
Not sure where/what this should be declared to: https://github.com/majestrate/wterm/blob/master/src/st.c#L4009

**Comment by majestrate** [comment]
it's set here: https://github.com/majestrate/wterm/blob/master/config.mk#L2

**Comment by MichaelMackus** [comment]
Oh, I see. Thank you, it might just be an error with my custom ebuild I will close for now.
