### ISSUE TITLE
no wayland shell

### ISSUE THREAD

**Issue by aecepoglu** [majestrate/wterm#7]
In "Velox" I am unable to start wterm.

I have wld-git (from AUR) installed alongside velox-git.

1. I start "termite" first (so I can see the stderr)
2. `wterm`
3. I get the error "no wayland shell"
4. `wterm -e /bin/bash`
5. Same error

**Comment by majestrate** [comment]
On Thu, Feb 21, 2019 at 01:18:34AM -0800, aecepoglu wrote:
> In "Velox" I am unable to start wterm.
> 
> I have wld-git (from AUR) installed alongside velox-git.
> 
> 1. I start "termite" first (so I can see the stderr)
> 2. `wterm`
> 3. I get the error "no wayland shell"
> 4. `wterm -e /bin/bash`
> 5. Same error

what revision of velox are you using?

**Comment by aecepoglu** [comment]
Must be the very last commit, considering [this is the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=velox-git) file that builds the program

(Didn't mean to close and reopen the issue)

**Comment by majestrate** [comment]
On Thu, Feb 21, 2019 at 05:20:49AM -0800, aecepoglu wrote:
> Must be the very last commit, considering [this is the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=velox-git) file that builds the program

what revision of swc is it using?

**Comment by aecepoglu** [comment]
It would again be the latest commit (since that too comes from the git repo).

I don't have access to that computer now but in 4 hours I can list versions of swc as well as every other library that you like.

**Comment by aecepoglu** [comment]
swc-git: r616.2f66cea-1
wld-git: r159.b4e902b-1
velox-git: 0.0.2.r278.g79e2e7d-1

The 2f66cea is the git commit addr for swc, which is the latest commit. Probably the others are the same.

**Comment by majestrate** [comment]
On Thu, Feb 21, 2019 at 12:25:21PM -0800, aecepoglu wrote:
> swc-git: r616.2f66cea-1
> wld-git: r159.b4e902b-1
> velox-git: 0.0.2.r278.g79e2e7d-1
> 
> The 2f66cea is the git commit addr for swc, which is the latest commit. Probably the others are the same.

I don't think wterm ever worked on velox to begin with as it lacks the right wayland protocol (specifically i think it's xdg desktop shell v6)

This project has been on my back burner for a while so patches for older compositors are welcome.

**Comment by aecepoglu** [comment]
I don't think I know enough about the wayland protocol to be able to fix the issue myself. When I have more time to invest into learning it, I'll surely come here and fix it. I need a decent terminal to run my editor in first, so I can edit the code.

I found this issue on velox and I'm not sure how relevant it is.

https://github.com/michaelforney/velox/issues/32

In that case I think you can close this and mark it "won't fix".

**Comment by majestrate** [comment]
not sure if it's a won't fix yet. it can be done but it'll take a bit of boilerplate.

**Comment by aecepoglu** [comment]
I no longer use this so this issue is no longer of concern to me. Please reopen if you think otherwise
